// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJUfmHYvpTZSuog3_72O8fKdS5_llfynQ',
    appId: '1:51162743754:web:f3b8eb3f3193bf24350533',
    messagingSenderId: '51162743754',
    projectId: 'digimag-b7aa0',
    authDomain: 'digimag-b7aa0.firebaseapp.com',
    storageBucket: 'digimag-b7aa0.firebasestorage.app',
    measurementId: 'G-BMCT9B4KXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEd8Vzijz_Ek7KGMOHt68BzejxMpACpEU',
    appId: '1:51162743754:android:d5b53a443b89d5aa350533',
    messagingSenderId: '51162743754',
    projectId: 'digimag-b7aa0',
    storageBucket: 'digimag-b7aa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU8tBlnWSP3lqVvhGtW33iLUqC4k9F92Y',
    appId: '1:51162743754:ios:20fbf702582c8d57350533',
    messagingSenderId: '51162743754',
    projectId: 'digimag-b7aa0',
    storageBucket: 'digimag-b7aa0.firebasestorage.app',
    androidClientId: '51162743754-3gdotm7voatedlm3vt0psjif0p3urhvg.apps.googleusercontent.com',
    iosClientId: '51162743754-08eniccirh6utqnv66tdghr6jneeqqi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.digimag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU8tBlnWSP3lqVvhGtW33iLUqC4k9F92Y',
    appId: '1:51162743754:ios:20fbf702582c8d57350533',
    messagingSenderId: '51162743754',
    projectId: 'digimag-b7aa0',
    storageBucket: 'digimag-b7aa0.firebasestorage.app',
    androidClientId: '51162743754-3gdotm7voatedlm3vt0psjif0p3urhvg.apps.googleusercontent.com',
    iosClientId: '51162743754-08eniccirh6utqnv66tdghr6jneeqqi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.digimag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJUfmHYvpTZSuog3_72O8fKdS5_llfynQ',
    appId: '1:51162743754:web:75e6899cf693a4f3350533',
    messagingSenderId: '51162743754',
    projectId: 'digimag-b7aa0',
    authDomain: 'digimag-b7aa0.firebaseapp.com',
    storageBucket: 'digimag-b7aa0.firebasestorage.app',
    measurementId: 'G-LGJ2NZDJHH',
  );
}
