// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgvpNqXXJkosNyT28IjB8zDrRogKEt7g0',
    appId: '1:1058201854206:web:afc83fa9c867dfb252c5af',
    messagingSenderId: '1058201854206',
    projectId: 'digimag-18314',
    authDomain: 'digimag-18314.firebaseapp.com',
    storageBucket: 'digimag-18314.firebasestorage.app',
    measurementId: 'G-FB60PXZ44B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCaX1hrrtgiBOvN64G2Y2DjaxE8AWkBn8',
    appId: '1:1058201854206:android:71581970b4bf8c2652c5af',
    messagingSenderId: '1058201854206',
    projectId: 'digimag-18314',
    storageBucket: 'digimag-18314.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz-V-E92676G0u7mPiLZ1wNfN_7R0rbTM',
    appId: '1:1058201854206:ios:1a6b4d760f6d557552c5af',
    messagingSenderId: '1058201854206',
    projectId: 'digimag-18314',
    storageBucket: 'digimag-18314.firebasestorage.app',
    iosBundleId: 'com.example.digimag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz-V-E92676G0u7mPiLZ1wNfN_7R0rbTM',
    appId: '1:1058201854206:ios:1a6b4d760f6d557552c5af',
    messagingSenderId: '1058201854206',
    projectId: 'digimag-18314',
    storageBucket: 'digimag-18314.firebasestorage.app',
    iosBundleId: 'com.example.digimag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgvpNqXXJkosNyT28IjB8zDrRogKEt7g0',
    appId: '1:1058201854206:web:189bc983a7dd64e252c5af',
    messagingSenderId: '1058201854206',
    projectId: 'digimag-18314',
    authDomain: 'digimag-18314.firebaseapp.com',
    storageBucket: 'digimag-18314.firebasestorage.app',
    measurementId: 'G-SXPYV0NZZH',
  );

}